### ISSUE TITLE
Data Loader: .from_jsonl()

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#16]
It'd be nice if we could also read data from disk. A syntax like this would be nice: 

```python
Clumper.from_jsonl(path, settings)
```

**Comment by samarpan-rai** [comment]
I could work on this as I have to regularly use jsonl file

**Comment by koaning** [comment]
Feel free to go for it. It would be nice to allow for a setting that sets the number of lines to read in. That way if the file is huge we only read in the top 1000 items or something.

**Comment by samarpan-rai** [comment]
I have a basic implementation of this issue that reads local file. I can improve it to also allow file in the cloud but I want to ensure that I can create test for it first. Therefore, would it be possible for @koaning to upload few sample jsonl files ? Perhaps in the same place as https://calmcode.io/datasets ?

**Comment by koaning** [comment]
I usually keep a `data` folder in the `tests` directory for this sort of thing. Feel free to create that and add a small file there. Since you've got a PR ready though, we should keep this conversation to the PR. Github issues are usually meant to discuss what features should go into a ticket. Implementation discussions should be had on the PR side.

**Comment by koaning** [comment]
This is now fixed.
