### ISSUE TITLE
Data Loader: .from_csv()

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#18]
It'd be nice if we could also read data from disk. A syntax like this would be nice: 

```python
Clumper.from_csv(path, settings)
```

**Comment by samukweku** [comment]
If it is ok with you, kindly assign this to me - I would love to work on this.

**Comment by koaning** [comment]
Sure thing, go for it! You might be able to use the standard `csv` module for this. One thing that would be nice to add: the ability the specify how many rows of data to read in. That way we might read only the top `n` rows of a very large file.

**Comment by samukweku** [comment]
somehow I cannot get my functions to run. How do I set up my workflow so that I can test the new function?

**Comment by koaning** [comment]
Just to check, you're familiar with pytest? If not you may appreciate [this tutorial](https://calmcode.io/pytest/introduction.html).

**Comment by samukweku** [comment]
yes I am familiar with pytest. I'm just baffled that I cant access the function I created in clumper.py. when I try running `clumper.read_csv` it says `read_csv not found`

**Comment by samukweku** [comment]
not pytest related; found my silly mistake. Thanks
