### ISSUE TITLE
Data Writer: csv

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#19]
Data Loader: .to_csv()

It'd be nice if we could also write data from disk. A syntax like this would be nice: 

```python
Clumper.to_csv(path, settings)
```

An important theme here is to keep it simple and to think how we might want to deal with keys that sometimes go missing.

**Comment by samukweku** [comment]
I'll take this on. Could you share an example of missing keys?

**Comment by koaning** [comment]
Sure thing. Consider this example; 

```python
from clumper import Clumper

data = [
  {'a': 1, 'b':2}, 
  {'c': 3}
]

Clumper(data).to_csv()
```

What should the csv look like?

**Comment by samukweku** [comment]
@koaning , the example is a good one. My approach would be to ensure every key is captured as the header of the csv table, and place None at points where keys are missing. Thinking about this as I write, I will add another test to `read_csv`, to see how it deals with nulls.  we should be able to get the same result when reading and writing.

**Comment by koaning** [comment]
It might be good to check how `pandas` might do this. I think another option is to just leave the fields empty. Also; I'm not sure what the best approach here is so I've got a somewhat open mind here. I think it is also fine if the first implementation of this is "fair and reasonable in most cases" instead of "perfect in all cases". I'm sure there's some international standards but we don't have to 100% comply to them immediately.
