### ISSUE TITLE
Data Writer: json/jsonl

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#20]
Data Loader: .to_json()/to_jsonl()

It'd be nice if we could also write data to disk. A syntax like this would be nice: 

```python
Clumper.to_json(path, settings)
Clumper.to_jsonl(path, settings)
```

**Comment by koaning** [comment]
Settings might include the max number of rows to read in.

**Comment by samarpan-rai** [comment]
> Settings might include the max number of rows to read in.

You mean write out?

**Comment by samarpan-rai** [comment]
Count me in this issue if someone hasn't started yet.

**Comment by koaning** [comment]
I think you can go ahead and pick this one up. I'll be taking your previous change for a new release so this change will be for the next one. But as far as I know nobody else is working on this.
