### ISSUE TITLE
Explode can remove data by accident.

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#31]
It seems that explode removes data at times. 

```python
from clumper import Clumper 

data = [
    {"name": "john", "series": []},
    {"name": "jane", "series": [1, 2]},
    {"name": "jack", "series": [1, 2, 3]},
]

Clumper(data).explode("series").collect()
```

This yields. 

```
[{'name': 'jane', 'series': 1},
 {'name': 'jane', 'series': 2},
 {'name': 'jack', 'series': 1},
 {'name': 'jack', 'series': 2},
 {'name': 'jack', 'series': 3}]
```

Note that `john` is gone.

Not 100% sure if this is behavior that I like. You can easily prevent it with a `mutate` before though. 

Need to think about this one.

**Comment by samukweku** [comment]
@koaning Possibly when exploding we could check for falsy or empty containers and replace with empty string or if numbers replace with 0.

**Comment by koaning** [comment]
That's a possibility. I'm not 100% what to think of this behavior. Part of me thinks that it can be confusing. Then again, there's something to be said that this is the right behavior.
