### ISSUE TITLE
Groups should return a copy.

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#43]
This issue was raised [here](https://twitter.com/mr_le_fox/status/1299295822048374785?s=20). If you look at our implementations you'll notice that we typically do not return self, rather a copy of self. This in order to keep things immutable. 

There currently is an exception to that rule though `groupby` and `ungroup` do not follow this pattern. As seen [here](https://github.com/koaning/clumper/blob/52cd63aac585ffec9146087afcac0122d05c9d9a/clumper/clump.py#L198).

**Comment by samarpan-rai** [comment]
Is it then simple as doing `deepcopy` on the resulted (un)group?

**Comment by koaning** [comment]
Pretty much.

**Comment by samarpan-rai** [comment]
You can assign it to me!
