### ISSUE TITLE
Reading in multiple files in one go. 

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#46]
**Is your feature request related to a problem? Please describe.**

I have a folder with lots and lots of json files. Can I read them in all at once? 

**Describe the solution you'd like**

It'd be nice if all of our readers allowed for a `'*'` or a `Path.glob` that allows you to read in lots of files at once. 

Something like: 

```python
Clumper.read_json("folder/*.json") 
Clumper.read_json(pathlib.Path("folder").glob("*"))
```

**Additional context**

As far as an implementation goes, we can probably solve this nicely with a decorator. Assuming the function that it wraps is a file-reader we should not need to touch the internal readers.

**Comment by samukweku** [comment]
@samarpan-rai I think this is in your ball park since you've worked extensively with the json files.

**Comment by koaning** [comment]
Anybody is free to pick it up but it can be a relatively advanced feature to write if you're unfamiliar with decorators. I want to have a decorator that you can add to these `read_json` but also `read_jsonl` and `read_csv` (potentially also `read_yaml` in the future).

**Comment by samukweku** [comment]
If so, assign it to me, so I  can build my understanding of decorators. @koaning could you provide a sample code of the decorator?

**Comment by koaning** [comment]
Haha the decorators are sort of "next up" for calmcode.io but I'm not sure when I'll get to that. I'm getting married this month so it isn't super high on the priority list. You might want to try [realpython](https://realpython.com/primer-on-python-decorators/). It's not as calm of a website and a bit spammy for email signups but the content tends to be good. 

Another thing you can do; there are a few decorators already written in this library. Feel free to check them out as well.

**Comment by koaning** [comment]
Actually now that I think of it, we do have one video on a decorator for pandas. It doesn't go into much depth on the decorator side of things but it does give a nice example of why decorators can be awesome. The content is listed under [pandas pipes](https://calmcode.io/pandas-pipe/introduction.html). Specifically the video on "logs".

**Comment by samukweku** [comment]
Happy wedding. Wish you all the best marriage has to offer. I'll work on this.

**Comment by samarpan-rai** [comment]
I would also like to give it a try. I think decorators are quite an advanced topic so it would be nice to have some experience with it.

**Comment by samarpan-rai** [comment]
I think I have a preliminary implementation. I am having some trouble with the test. My idea was to read multiple files and assert that the length is correct.  However, I am having trouble with data for the test. We currently only have one file per extension, so testing becomes rather mundane. For the moment, I am making copies locally to test it, but I don't want to push with double files. Any ideas?

**Comment by koaning** [comment]
1. Pytest has a tmpdir that allows you to write a file to a temporary directory. One could write three files there, temporarily, just for the sake of the test. 
2. I'm open to you having a go at it @samarpan-rai but @samukweku also mentioned interest in working on this feature and is also assigned to this feature. If you want to collaborate then totally go for it, but it'd be good to reach out to @samukweku too.

**Comment by samarpan-rai** [comment]
@koaning I'll look into that

@samukweku shall we talk about how we can collaborate on this issue?

**Comment by samukweku** [comment]
@samarpan-rai it is fine if you do it. I'll learn from your implementation. @koaning Kindly reassign to him

**Comment by koaning** [comment]
I've assigned it to both of you. Since I'm a bit busy in the next few weeks (wedding) it might be a fun exercise for you two to collaborate and review each-others work.

**Comment by koaning** [comment]
One thing to perhaps discuss upfront. Do we want to support this as well? 

```python
Clumper.read_json("folder/file_1.json", "folder/file_2.json", "folder/file_3.json") 
```

**Comment by samukweku** [comment]
I dont think we should. separating single and multiple files seems to be an easier and more maintainable approach

**Comment by samarpan-rai** [comment]
@koaning Gefeliciteerd! 

I agree with @samukweku. It makes things more complicated. I would suggest we support the following inputs for reading jsonl

```python
# Using string
Clumper.read_jsonl("folder/*.jsonl")
Clumper.read_jsonl("folder/*.jsonl", n=50) # 50 lines per found file

# Using Path.glob
Clumper.read_jsonl(pathlib.Path("folder").glob("*.jsonl"))
Clumper.read_jsonl(pathlib.Path("folder").glob("*.jsonl"), n=50) # 50 lines per found file
```

I am having some trouble with accessing the `path` argument in the decorator, maybe we can discuss how to solve it? We could discuss it in this issue but it would be unnecessarily bloated with messages so I suggest we talk in some chat platform. Is there any platform you prefer to talk in? I can create a room in gitter for these discussions as it has easy integration with github.

**Comment by samukweku** [comment]
@samarpan-rai maybe you can do a pull request and we can look at it together?

**Comment by samarpan-rai** [comment]
> @koaning Gefeliciteerd!
> 
> I agree with @samukweku. It makes things more complicated. I would suggest we support the following inputs for reading jsonl
> 
> ```python
> # Using string
> Clumper.read_jsonl("folder/*.jsonl")
> Clumper.read_jsonl("folder/*.jsonl", n=50) # 50 lines per found file
> 
> # Using Path.glob
> Clumper.read_jsonl(pathlib.Path("folder").glob("*.jsonl"))
> Clumper.read_jsonl(pathlib.Path("folder").glob("*.jsonl"), n=50) # 50 lines per found file
> ```
> 
> I am having some trouble with accessing the `path` argument in the decorator, maybe we can discuss how to solve it? We could discuss it in this issue but it would be unnecessarily bloated with messages so I suggest we talk in some chat platform. Is there any platform you prefer to talk in? I can create a room in gitter for these discussions as it has easy integration with github.

Update on this:
We are only going to support using string. Using glob was an overkill as the string gets converted to glob anyway. 
```python
 # Using string
Clumper.read_jsonl("folder/*.jsonl")
Clumper.read_jsonl("folder/*.jsonl", n=50) # 50 lines per found file
```

**Comment by koaning** [comment]
@samarpan-rai are these changes reflected in the current PR?

**Comment by koaning** [comment]
This is now merged.

**Comment by samarpan-rai** [comment]
> @samarpan-rai are these changes reflected in the current PR?
Implicitly yes, I only continue with reading the pattern if there is * in the path parameter. I believe providing glob directly will throw error.
