### ISSUE TITLE
Add tests for reading in yaml files with wildcard 

### ISSUE THREAD

**Issue by samarpan-rai** [koaning/clumper#54]
The current test only checks for json, csv and jsonl. https://github.com/koaning/clumper/blob/master/tests/test_decorator/test_multifile.py

Side note : should we rename multifile to wildcard wrapper as you are calling it something different in the changelog and documentation?

**Comment by koaning** [comment]
Can't hurt to have this. Go for it 👍

**Comment by samarpan-rai** [comment]
@koaning have you seen this?
> Side note : should we rename multifile to wildcard wrapper as you are calling it something different in the changelog and documentation?

**Comment by koaning** [comment]
It's better to change the changelog if my choice of words does not reflect the correct name in the code.

**Comment by samarpan-rai** [comment]
I would argue that "wildcard" sounds more correct than "multifile". What do you think?
