### ISSUE TITLE
Dictionaries are Causing Issues

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#57]
Let's say this is the input. 

```python
d = {
  'name': 'name',
 'image': 'img.img',
 'short': 'something short',
 'tags': ['science', 'entertainment'],
 'videos': [{'name': 'Intro',
   'url': 'https://player.vimeo.com/video/414517859'},
  {'name': 'Code', 'url': 'https://player.vimeo.com/video/414517885'},
  {'name': 'Plotting', 'url': 'https://player.vimeo.com/video/414517957'},
  {'name': 'How it Works 1',
   'url': 'https://player.vimeo.com/video/414518015'},
  {'name': 'How it Works 2',
   'url': 'https://player.vimeo.com/video/414518059'},
  {'name': 'Accuracy', 'url': 'https://player.vimeo.com/video/414518106'},
  {'name': 'Benchmark', 'url': 'https://player.vimeo.com/video/414518141'},
  {'name': 'Final Features',
   'url': 'https://player.vimeo.com/video/414518199'}]
}
```

Then what should come out of this? 

```python
Clumper(d).map(lambda d: [d]).collect()
```

Not this; 

```python
[['name'], ['image'], ['short'], ['tags'], ['videos']]
```

Yet that is exactly what is happening! The root cause for this is that we currently allow dictionaries to be read in via all of our `read_` functions. The issue lies in the `map` method. It assumes a list of dictionaries. We should consider a decorator that can detect this but maybe we should also be more strict when we create a clumper object.

**Comment by samukweku** [comment]
I'll have a look at this, and try and submit a fix.

**Comment by koaning** [comment]
@samukweku what decorator are you referring to? 

I'm wondering if it makes sense to add a method, like `flatmap` that flattens the blob into a one dimensional list.

**Comment by samukweku** [comment]
>...The root cause for this is that we currently allow dictionaries to be read in via all of our read_ functions. The issue lies in the map method. It assumes a list of dictionaries. **We should consider a decorator that can detect this** but maybe we should also be more strict when we create a clumper object.

Maybe I assume wrongly, but I thought all `read_*`  functions returned a list of dictionaries. I'm usually wary of more function names, and that is my personal opinion. Just feel we could slot it into `map` to take care of cases where Clumper is not a list of dictionaries. Unless you think it would have an adverse effect ?

**Comment by koaning** [comment]
> I thought all read_* functions returned a list of dictionaries

For the [calmcode.io](https://calmcode.io) project I want to be able to read in many yaml files. Something like; 

```python
Clumper.read_yaml("calmcode/content/*.yml")
```

The annoying thing is that *here* the same problem occurs. The read functions currently do not return a list of dictionaries. I think it can be fine to also allow dictionaries because that makes the library more flexible (there's **a lot** of nasty data out there) but I'm thinking about adding a flag to the `read_` methods that turn a dictionary into a list containing the single dictionary.

**Comment by koaning** [comment]
Should be fixed now by https://github.com/koaning/clumper/pull/60
