### ISSUE TITLE
New Verb: Sample

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#6]
It'd be nice if we could randomly sample from a clumper collection.

The API should allow for:

- **n**: the number of items to sample
- **frac**: the fraction of items to sample 
- **replace**: if we should replace items yes/no
- **weights**: a key that can be passed in, associating it's value of the probability of being drawn 
- **random_state**: the random seed used for sampling

**Comment by koaning** [comment]
Come to think of it. It might be nicer to split out `sample_n` and `sample_frac`.

**Comment by samarpan-rai** [comment]
After some hiatus, I would like to work on this if there are no takers.

**Comment by koaning** [comment]
Go for it :)

**Comment by samarpan-rai** [comment]
I am having trouble interpreting what `weights` would look like. I am guessing it would be a dict like the following.

```python

{'key1' : 0.1, 'key2: 0.5, 'key3': 0.4}

```

Is this a correct assumption?

Further questions: 

1. I learn recently about static typing in python. Can we use it for parameter definition?
2. Do both functions `sample` and `sample_frac` have the same parameter except the `n` and `frac`?
3. Should we set default `random_state` i.e 42 ?

I have created a new PR with dummy methods here https://github.com/koaning/clumper/pull/83

**Comment by koaning** [comment]
I was thinking similar to how [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) handles it. 

The idea is that if we have a Clumper with the following content:

```python
c = Clumper([{'w':0.1, 'val':'a'}, {'w': 0.2, 'val': 'b'}])
```

That if we call `c.random(n=1)` the probability of getting either dictionary is equal while `c.random(n=1, key='w')` would prefer the second dictionary.

**Comment by koaning** [comment]
I'm open to doing more things with typing in this library but I haven't found a type-checker that I really like. I'm also not 100% sure if I want to wait until python3.6 is no longer supported. Once 3.7 is supported we no longer would need to use `-> "Clumper"` and we could instead use `-> Clumper` directly.

**Comment by koaning** [comment]
Setting random_state to 42 sounds fine to me!

**Comment by samarpan-rai** [comment]
> I was thinking similar to how [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) handles it.
> I'm open to doing more things with typing in this library but I haven't found a type-checker that I really like. I'm also not 100% sure if I want to wait until python3.6 is no longer supported. Once 3.7 is supported we no longer would need to use `-> "Clumper"` and we could instead use `-> Clumper` directly.

I don't understand the difference between `-> "Clumper"`  and `-> Clumper`. Can you elaborate further ?


> The idea is that if we have a Clumper with the following content:
> 
> ```python
> c = Clumper([{'w':0.1, 'val':'a'}, {'w': 0.2, 'val': 'b'}])
> ```
> 
> That if we call `c.random(n=1)` the probability of getting either dictionary is equal while `c.random(n=1, key='w')` would prefer the second dictionary.

The example is clear but you mean to say `c.sample(..)` right or is there already a random method that I didn't see. In any case, are we allowed to more than one "key" ? If so, are we going to normalize it by columns first and then normalize by rows? What if there are missing values? 

Pandas doc says "If weights do not sum to 1, they will be normalized to sum to 1. Missing values in the weights column will be treated as zero. Infinite values not allowed." Should we follow the same idea or do you have something else in mind?

**Comment by koaning** [comment]
Ah. `c.sample(..)` is indeed correct 😅 . 

What pandoc says sounds like a valid thing for us to do. 

In python3.6 when you add types to a method of a class, you cannot refer to the class. So you gotta do this. 

```
class Thing:
    def __init__(self, thing):
        self.thing = thing

    def pipe(self, func) -> "Thing":
        # Note the string output here.
        self.thing = func(thing)
        return self
```

In python 3.7 a cleaner syntax is possible.

```
class Thing:
    def __init__(self, thing):
        self.thing = thing

    def pipe(self, func) -> Thing:
        # Note the string output here.
        self.thing = func(thing)
        return self
```

**Comment by samarpan-rai** [comment]
> Ah. `c.sample(..)` is indeed correct sweat_smile .
> 
> What pandoc says sounds like a valid thing for us to do.
> 
> In python3.6 when you add types to a method of a class, you cannot refer to the class. So you gotta do this.
> 
> ```python
> class Thing:
>     def __init__(self, thing):
>         self.thing = thing
> 
>     def pipe(self, func) -> "Thing":
>         # Note the string output here as type.
>         self.thing = func(thing)
>         return self
> ```
> 
> In python 3.7 a cleaner syntax is possible.
> 
> ```python
> class Thing:
>     def __init__(self, thing):
>         self.thing = thing
> 
>     def pipe(self, func) -> Thing:
>         # Note no string output here as type.
>         self.thing = func(thing)
>         return self
> ```

Thanks for making it clear!

**Comment by samarpan-rai** [comment]
I have another question for us: I am trying to implement a test to check when we sample with replacement. It could be that there are no replacements due to randomness so a test checking that there should be at least one repeated value could value. I can mitigate this by using a large n but it really depends on data set size. I cannot think of an elegant solution. Any ideas?

**Comment by koaning** [comment]
When writing a test, we're often interested in testing the code that *we* write. If we're using the `random` module under the hood we have to assume that it is correctly implemented. It doesn't make too much sense for the `clumper` library to write tests that ensure that the `random` submodule has correct implementations.

Testing randomness is hard in general, so the main thing to focus on is to write tests for the edge cases. Things like; 

- When there's only one element but we resample, it should resample that one element. 
- If we assign weights, they must be positive or otherwise we'll throw an error. 
- If the weights are zero we should never sample it. 

Tests are a protection mechanism but they are not a "100% guaranteed insurance policy". And that's fine.

**Comment by samarpan-rai** [comment]
> When writing a test, we're often interested in testing the code that _we_ write. If we're using the `random` module under the hood we have to assume that it is correctly implemented. It doesn't make too much sense for the `clumper` library to write tests that ensure that the `random` submodule has correct implementations.
> 
> Testing randomness is hard in general, so the main thing to focus on is to write tests for the edge cases. Things like;
> 
>     * When there's only one element but we resample, it should resample that one element.

I will add this as test.

>     * If we assign weights, they must be positive or otherwise we'll throw an error.
> 
>     * If the weights are zero we should never sample it.

So the test would check that each individual row which had a cumulative score of 0 should not be sampled? Seems like quite a verbose test. 


> Tests are a protection mechanism but they are not a "100% guaranteed insurance policy". And that's fine. As long as the tests serve as a double-checking mechanism I'd say they're doing their job well enough.

Good point!


Question: Do you perhaps know any good implementation of pure python that uses probability distribution for sampling _without_ replacement? Python's `random.choices()` function only allows for sampling _with_ replacement. My current approach uses "weights" in the sense that each row is assigned an integer value rather than a probability of being sampled. This creates some problem in the implementation as the summed up weights have to be converted to integers where we may loose precision in sampling.

**Comment by koaning** [comment]
Let's prevent split-brain and discuss anything related to the implementation in the actual PR.

**Comment by koaning** [comment]
It was implemented here: https://github.com/koaning/clumper/pull/83
