### ISSUE TITLE
[FEATURE] Have multifile support Path objects

### ISSUE THREAD

**Issue by daddycocoaman** [koaning/clumper#65]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Ideally, the `multifile` decorator should support parsing `List[pathlib.Path]` and `List[str]` instead of relying on the asterisk in a path. Currently, it takes a URI which may or may not have an asterisk in it and handles all the parsing. A user should be able to pass a list for it to instead. Since [pathlib also includes glob and is available in Python 3.4+](https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob), it should be pretty trivial. 

**Describe alternatives you've considered**
It currently works as written so no alternatives. I think this feature request would improve its functionality. It also feels a lot more natural to pass Path objects than using the `glob` module itself.

**Additional context**
N/A

**Comment by koaning** [comment]
We use pathlib internally so this sounds very sensible. 

That said; if you pass a string with a glob (like `"folder/file-*.json"`) it should already pick up the files.

**Comment by koaning** [comment]
Also, @daddycocoaman I just gave [this a listen](https://mcohmi.bandcamp.com/track/brand-new-era). Just makin' sure it's said; you got some talent there.

**Comment by daddycocoaman** [comment]
Thanks for the listen and the compliment!

I used the asterisk form in my project like this:

```python
clumper = Clumper.read_json(str(Path(app_dir) / "ServiceTags_*.json"))
```

but I guess I would have preferred this:

```python
clumper = Clumper.read_json(Path(app_dir).glob("ServiceTags_*.json"))
```
I'll make a PR this weekend that supports both forms so that it doesn't break anything.

**Comment by koaning** [comment]
If you're going to make this change, be sure to make it [here](https://github.com/koaning/clumper/blob/master/clumper/decorators.py#L65-L121). We've got a decorator that handles the multi-file use-case. That way it will also work for yaml/csv/jsonl and this will keep the API consistent.
