### ISSUE TITLE
Add a helper to filter in/out examples that do not fit a `Pydantic` validator

### ISSUE THREAD

**Issue by koaning** [koaning/clumper#72]
It should probably be a `.pipe()`-helper.

**Comment by FBruzzesi** [comment]
@koaning this and #73 should both be doable with `.pipe`, a custom function and a pydantic schema. Are you still interested in these developments?

**Comment by koaning** [comment]
The more that I think about it, the more that it's probably out of scope for this project. I've been using clumper for months and I still haven't hit this use case. I'm also a bit weary to add a dependency to this repository because I'm pretty proud that we currently only have one optional dependency. 

You're right to point out the other issue though. I'll close both issues.

**Comment by FBruzzesi** [comment]
I believe pydantic may actually not be required, at least not for #73 (which I think it's very close related to #77 as well). 
Maybe I am missing something but a work around may be a function with a base/default clump, such as:
```python
from clumper import Clumper

pokemon = [
    {'name': 'Bulbasaur', 'total': 318, 'hp': 45, 'attack': 49},
    {'name': 'Ivysaur', 'total': 405, 'attack': 62},  # missing hp
    {'name': 'Venusaur', 'total': 525, 'hp': 80},  # missing attack
]
base_pokemon = {'name': 'Charmander', 'total': 309, 'hp': 39, 'attack': 52}
clump = Clumper(pokemon)

def from_default(clump, base_clump):
    return Clumper([{**base_clump, **d} for d in clump])
    
clump.pipe(from_default, base_pokemon).collect()
[{'name': 'Bulbasaur', 'total': 318, 'hp': 45, 'attack': 49},
 {'name': 'Ivysaur', 'total': 405, 'hp': 39, 'attack': 62},
 {'name': 'Venusaur', 'total': 525, 'hp': 80, 'attack': 52}]
```

(Which I know it doesn't really make sense for pokemon's attributes)

**Comment by koaning** [comment]
Your example is a nice one but I suppose in this example you could've also used `map`. 

```python
base_pokemon = {'name': 'Charmander', 'total': 309, 'hp': 39, 'attack': 52}

clump.map(lambda d: {**base_pokemon, **d)}
```

An impute method wouldn't hurt though.

**Comment by koaning** [comment]
Come to think of it, I suppose impute could be easily implemented via; 

```python
def impute(self, **kwargs):
    return self.map(lambda d: {**kwargs, **d})
```

**Comment by FBruzzesi** [comment]
Just one consideration for such `impute` method, one should be very careful. One example that would break:
 ```python
from clumper import Clumper

class Clumper_(Clumper):
    def impute(self, **kwargs):
        return self.map(lambda d: {**kwargs, **d})
    
pokemon = [
    {'name': 'Bulbasaur', 'type': {'primary': 'grass', 'secondary': 'poison'}},
    {'name': 'Ivysaur', 'type': {'primary': 'grass'}},
    {'name': 'Venusaur'}
]

clump = Clumper_(pokemon)
clump.impute(type={'primary': 'grass', 'secondary': 'poison'}).collect()
[{'type': {'primary': 'grass', 'secondary': 'poison'}, 'name': 'Bulbasaur'},
 {'type': {'primary': 'grass'}, 'name': 'Ivysaur'},
 {'type': {'primary': 'grass', 'secondary': 'poison'}, 'name': 'Venusaur'}]
```
which, I would argue, is not what to be expected (notice that a similar issue would happen if `type` is a list).

With such example in mind, I followed the white rabbit and found [this answer](https://stackoverflow.com/a/7205107/12411536) very useful, and implemented with few changes to deal with the list case and with a key already present, would handle the above cases:
 ```python
from clumper import Clumper

class Clumper_(Clumper):
    def merge(self, a, b, path=None):
        "merges b into a"
        
        if path is None:
            path = []
        
        for key in b:
            if key in a:
                if isinstance(a[key], dict) and isinstance(b[key], dict):
                    self.merge(a[key], b[key], path + [str(key)])
                elif isinstance(a[key], list) and isinstance(b[key], list):
                    a[key] = list(set(a[key] + b[key]))
                else:
                    pass  # key in a has different value than the one to impute
            else:
                a[key] = b[key]
        return a

    def impute(self, **kwargs):
        import copy
        return self.map(lambda d: self.merge(copy.deepcopy(d), kwargs))
    
pokemon = [
    {'name': 'Bulbasaur', 'type': {'primary': 'grass', 'secondary': 'poison'}},
    {'name': 'Ivysaur', 'type': {'primary': 'grass'}},
    {'name': 'Venusaur'}
]

clump = Clumper_(pokemon)
clump.impute(type={'primary': 'grass_imputed', 'secondary': 'poison'}).collect()
[{'name': 'Bulbasaur', 'type': {'primary': 'grass', 'secondary': 'poison'}},
 {'name': 'Ivysaur', 'type': {'primary': 'grass', 'secondary': 'poison'}},
 {'name': 'Venusaur', 'type': {'primary': 'grass_impute', 'secondary': 'poison'}}]
 ```

And similarly in the list case (edit: this should and could be improved further depending on the behaviour to expect):
 ```python
pokemon = [
    {'name': 'Bulbasaur', 'type': ['Grass', 'Poison']},
    {'name': 'Ivysaur', 'type': ['Grass']},
    {'name': 'Venusaur'}
  ]

clump = Clumper_(pokemon)
clump.impute(type=['Grass', 'Poison']).collect()
[{'name': 'Bulbasaur', 'type': ['Grass', 'Poison']},
 {'name': 'Ivysaur', 'type': ['Grass', 'Poison']},
 {'name': 'Venusaur', 'type': ['Grass', 'Poison']}]
 ```

**Comment by koaning** [comment]
> which, I would argue, is not what to be expected (notice that a similar issue would happen if the type is a list).

I think I see what you mean there, but I feel a danger of scope creep here. One could say that we might want to implement a `impute()` and a `deep_impute()` to accommodate different behavior. But then the next question is; what do we do if `{'name': 'Venusaur', 'type': None}`. Should this also be imputed? 

I'm wondering if it may be best not to implement this feature and have the end-user think about it instead. I'd like to defer responsibility to the end-user as much as possible, partially because usually that prevents a lot of scope creep, but also because it usually empowers them to think about their problem a bit more.

**Comment by FBruzzesi** [comment]
- This may be very opinionated, yet I believe that a `deep_impute` method should impute any value for which `d.get(key)` is `None`, where `d` any (sub)dictionary of the clump - in my opinion, such a method, although being opinionated is very clear in its intent. 
  - Remark that dealing with list as end leaves is not trivial, and, for few cases that I dealt with, I think order should matter i.e. I would expect the following behaviour:
  ```python
  clump = Clumper([{'a': ['b']}])
  clump.impute({'a': ['c', 'd']}).collect()
  [{'a': ['b', 'd']}]
  ```
- On the other hand:
  ```python
  def impute(self, **kwargs):
      return self.map(lambda d: {**kwargs, **d})
  ``` 
  has few borderline cases which is hard to account for in full generality.

- I wonder if we should move this conversation to #77 so that people can see which possible options/drawbacks they have when it comes to impute values.
